### ISSUE TITLE
Link "Create a new wallet" is wrong

### ISSUE THREAD

**Issue by Fabryprog** [scryptachain/scrypta-manent-app#9]
HOT TO REPRODUCE IT

Into first screen i clicked to "Import existing account" and than the link "Create a new wallet" don't work!

![](https://cdn.discordapp.com/attachments/586279831600103445/624558131804110849/20190920_125041.jpg)

**Comment by turinglabsorg** [comment]
fixed, the back link was wrong. Now it's fixed, even the text is changed to a simply "go back"
